### ISSUE TITLE
Why not move the decorator parameters into a parameter for the decorator?

### ISSUE THREAD

**Issue by skewty** [furkanonder/objerve#1]
Found you RFC post on Reddit and here are my comments:

I don't like the unnecessary modification of the class.

Why have: `watch_dict = {"foo": "set", "bar": "get", "baz": "del", "qux": "set"}`
When you can have: `@watch({"foo": "set", "bar": "get", "baz": "del", "qux": "set"})`
Or perhaps better yet: `@watch(set={"foo", "qux"}, get={"bar"}, del={"baz"})` where the sets could be any iterable like list or tuple.

**Comment by furkanonder** [comment]
The [feature](https://github.com/furkanonder/objerve/commit/b11465ecc84d8dfa24752fe6f55c7fd9ea5b7e64) has been merged.

**Comment by skewty** [comment]
Perhaps the documentation should be updated before this issue is closed?

**Comment by furkanonder** [comment]
> Perhaps the documentation should be updated before this issue is closed?
You can see the updated documentation [here](https://github.com/furkanonder/objerve/tree/develop#readme)
